CREATE DATABASE QLGIAY

CREATE TABLE CHINHANH(
MACN INT IDENTITY(1,1) PRIMARY KEY,
TENCN NVARCHAR(50) NOT NULL,
)
CREATE TABLE SHOP(
MASHOP INT IDENTITY(1,1) PRIMARY KEY,
TENSHOP NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(100) NOT NULL,
STD NVARCHAR(20) NOT NULL UNIQUE,
MACN INT NOT NULL,
FOREIGN KEY (MACN) REFERENCES CHINHANH (MACN)
)
CREATE TABLE HANGGIAY(
MAHANG INT IDENTITY(1,1) PRIMARY KEY,
TENLOAI NVARCHAR(50) NOT NULL
)
CREATE TABLE LOAIGIAY(
MALOAI INT IDENTITY(1,1) PRIMARY KEY,
TENLOAI NVARCHAR(50) NOT NULL
)
CREATE TABLE SIZE(
MASIZE INT IDENTITY(1,1) PRIMARY KEY,
KICHCO NVARCHAR(50) NULL,
GIA NVARCHAR(50) NOT NULL,
)
CREATE TABLE GIAY(
MAGIAY INT IDENTITY(1,1) PRIMARY KEY,
TENGIAY NVARCHAR(50) NOT NULL,
MOTA NVARCHAR(50) NOT NULL,
SOLUONG NVARCHAR(50) NOT NULL,
MALOAI INT NOT NULL,
MAHANG INT NOT NULL,
MASIZE INT NOT NULL,
MASHOP INT NOT NULL,
FOREIGN KEY (MASHOP) REFERENCES SHOP (MASHOP),
FOREIGN KEY (MALOAI) REFERENCES LOAIGIAY (MALOAI),
FOREIGN KEY (MAHANG) REFERENCES HANGGIAY (MAHANG),
FOREIGN KEY (MASIZE) REFERENCES SIZE (MASIZE),
)
CREATE TABLE KHACHHANG(
MAKH INT IDENTITY(1,1) PRIMARY KEY,
TENKH NVARCHAR(50) NULL,
SDTKH NVARCHAR(20) NOT NULL UNIQUE,
GIOITINH INT NOT NULL,
)
CREATE TABLE HOADON(
MAHD INT IDENTITY(1,1) PRIMARY KEY,
NGAYLAP DATE NOT NULL,
TONGSOLUONG INT NOT NULL,
TONGTIEN FLOAT NOT NULL,
MASHOP INT NOT NULL,
MAKH INT NOT NULL,
FOREIGN KEY (MASHOP) REFERENCES SHOP (MASHOP),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
)
CREATE TABLE CTHOADON(
MAHD INT NOT NULL, 
MAGIAY INT NOT NULL,
SOLUONG INT NOT NULL,
GIAGIAY FLOAT NOT NULL,
TONGGIA FLOAT NOT NULL,
PRIMARY KEY(MAHD,MAGIAY),
FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
FOREIGN KEY (MAGIAY) REFERENCES GIAY (MAGIAY),
)

